#!/bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
	echo Your email $email satisfies Git Policy
	exit 0
else
	echo "Your email $email doesn't satisfy Git Policy"
	exit 1
fi
